# SEO Defaults
url: "https://pawanyd.github.io"
timezone: Asia/Kolkata # Your timezone
title: "Pawan Kumar - Principal Software Developer"
description: "Results-driven Principal Software Developer with 9+ years of experience in developing high-quality web applications"
author:
  name: "Pawan Kumar"
  twitter: "@pawanyd"
# Add these to existing config
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-postcss
  - jekyll-paginate
  - jekyll-feed

paginate: 3
paginate_path: "/blog/page:num/"

postcss:
  cache: true
